### ISSUE TITLE
Unable to save any file in micropython device

### ISSUE THREAD

**Issue by Athar-Naveed** [Athar-Naveed/eva-b#1]
Whenever I try to save a file in a micropython device (esp32-cam), it throws an error.
```
self.height // 8\n        self.buffer = bytearray(self.pages * s'): '').
See Thonny's backend.log for more info.

Process ended with exit code 1.
// that was while trying to save ssd1306.py
```
and this one,
```
Traceback (most recent call last):
  File "/home/atharnaveed/apps/thonny/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/atharnaveed/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 590, in on_double_click
    self.open_file(path)
  File "/home/atharnaveed/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 1205, in open_file
    get_workbench().get_editor_notebook().show_remote_file(path)
  File "/home/atharnaveed/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1076, in show_remote_file
    return self.show_file(make_remote_path(target_filename))
  File "/home/atharnaveed/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1063, in show_file
    self.select(editor)
  File "/home/atharnaveed/apps/thonny/lib/python3.10/tkinter/ttk.py", line 885, in select
    return self.tk.call(self._w, "select", tab_id)
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook.!editor2 is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook
```
Also I think that the old code is not getting updated. Like, I added the blink LED code, and even after resetting the led is still blinking, no matter whatever I do.

**Comment by Athar-Naveed** [comment]
I solved this issue, by erasing all the data from the esp32-cam using esp-tools this command,
```bash
esptool.py --chip esp32 --port /dev/ttyUSB0 erase_flash
```
and then loaded the firmware again, through this command,
```bash
esptool.py --chip esp32 --port /dev/ttyUSB0 write_flash -z 0x1000 micropython_camera_feeeb5ea3_esp32_idf4_4.bin
```
make sure to change the port after, __--port__, and add the name of your firmware (bin) file after, **0x1000**.
I think it was because of the storage issue, that the new data wasn't being written, and the esp32 wasn't getting refreshed.
